### PR TITLE
Upgrade to Ember 2.11

### PR DESCRIPTION
**Pull request by sandersky**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG

* **Upgraded** to Ember 2.11.

### CODE REVIEW

**Review by cstolli — APPROVED** [review]

**Comment by cstolli** [comment]
👍 


[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/94/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:
### No changes

**Comment by rox163** [comment]
This works? As of just a few days ago I had this issue https://github.com/ciena-frost/ember-frost-modal/issues/93
I don't see a new LF release out yet

**Comment by sandersky** [comment]
@rox163 `"liquid-fire": "0.27.2",` got rid of that error for me.

**Comment by rox163** [comment]
I don't see that one in the LF release list on gh but I see it npm :( I had tried the upgrade just last week and ended up reverting it all. Grr.

**Pull request merged**
