### PR TITLE
update version ember-frost-core

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG
* Use the latest `ember-frost-core`, with a flexible minor version (`^3.0.1`)

### CODE REVIEW

**Comment by juwara0** [comment]
The blueprint will need to be updated as well.

**Review by notmessenger — CHANGES_REQUESTED** [review]
* The blueprint needs to be updated as well.
* This cannot be a patch, must be a major, because you have changed a major version of a dependency, not a dev dependency.

**Comment by juwara0** [comment]
This will need to be a server major since you are moving the version of core up a major.

**Review by notmessenger — APPROVED** [review]

**Comment by notmessenger** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/117/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Pull request merged**
