### PR TITLE
Enable visual acceptance test

### PR DESCRIPTION
**Pull request by dafortin**
### This project uses [semver](semver.org), please check the scope of this pr:
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change
# CHANGELOG
- Enable visual acceptance test
- Switch from Firefox to Chrome for testing env.

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:

## New

#### Chrome: about

 

#### Chrome: about-with-product

 

#### Chrome: about-with-multiple-verions

 

#### Chrome: about-with-product-and-multiple-verions

 

#### Chrome: confirm

 

#### Chrome: error-dialog

 

#### Chrome: info

 

#### Chrome: warning-dialog

**Comment by dafortin** [comment]
I noticed that we are doing this for almost every visual acceptance test:

```
        this.$('.frost-modal-outlet-container.message').ready(() => {
          return capture(<name>, {
             ...
          }).then(() => {
            done()
          }).catch((err) => {
            done(err)
          })
```

Maybe we should wrap the capture in this to avoid repeating that code every time?

**Comment by sglanzer-fire** [comment]
I was under the impression that visual acceptance was supposed to allow the capture without a full promise resolve, @EWhite613 am I wrong about that?

e.g. I should be able to just call `return capture(<name>)`

**Comment by sglanzer-fire** [comment]
@dafortin Do we have the Chrome captures as well?  The Firefox captures seem to be missing a lot of svgs

**Comment by dafortin** [comment]
@sglanzer 
We are getting issues with the capture if we are doing only return. The modal is not fully rendered when we are calling html2 there is missing elements and html2 is crashing with `removeAttributes on null`

If I'm running with Chrome on travis I'm getting issues. I might be wrong but I think travis is not supporting Chrome. It's supporting Firefox and Phantom.

I can always do something like this: https://swizec.com/blog/how-to-run-javascript-tests-in-chrome-on-travis/swizec/6647

If you give me the go for this, I will switch it to use chrome.
I think we should use Firefox and Chrome. What is your opinion about this?

**Comment by sglanzer-fire** [comment]
Ignoring the Karma part (Testem is fine), yes we should setup Travis to use Chrome - this link may be more concise http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/

I'd prefer to stick to one browser for now since the test runs take long enough as-is

Re: return only - sure, but it _should_ work ;)

**Comment by dafortin** [comment]
@sglanzer Re: return only - sure, but it should work ;) => that's what I was expecting too or at least I'm expecting that ember-cli-visual-acceptance will handle it by wrapping it or something like that. I wish the user of visual acceptance won't have to do this :(.

**Comment by sglanzer-fire** [comment]
@dafortin full support to go fix that behavior to be implicit 👍

**Comment by dafortin** [comment]
@sglanzer  Yeahh :) Should we fix it with the current solution we are using `$(...).ready(...)` or we should figure another way to do it?

**Comment by sglanzer-fire** [comment]
I'm open to suggestions, the more we can abstract on this without losing capabilities the better

**Comment by dafortin** [comment]
I will submit this as is once it's building with Chrome and then raise another PR once the changes to visual acceptance are done.

Ready for approval. Test are running with Chrome.

**Comment by EWhite613** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/47/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Pull request merged**
