### PR TITLE
update ember-frost-core to latest major

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG
* Update `ember-frost-core` to latest major

### CODE REVIEW

**Comment by notmessenger** [comment]
@EWhite613 Prefer to have this addressed by #123 unless you need it sooner than in a few weeks (estimated timeframe of when #123 will be addressed).

**Comment by EWhite613** [comment]
@notmessenger looks like we wanna get this in

I believe we'll only need to update this addon and one of the internal ones in order for Ember to pick it up in the product.

But if we want uniformity I can update the rest as well.

**Review by notmessenger — CHANGES_REQUESTED** [review]
There are many reasons that this PR is not going to be merged:

a) There are no functionality differences between `^4.1.0` and `^5.1.0` of `ember-frost-core`

b) The `^5.1.0` of `ember-frost-core` did change a bunch of dependency stuff that may very likely have larger impacts on this repo then you are aware of

c) the upgrade to `^5.1.0` is being managed as part of FROST-570 and need to be performed in a specific order

d) The upgrading of a **dependency** to a new major version requires this PR to be released as a MAJOR and not a PATCH

e) There are a lot of other dependency changes that need to be made as well when `ember-frost-core` is upgraded to `^5.1.0` that were not made in this PR (the ones from #123 and subsequent repos updated before this one)

f)
> I believe we'll only need to update this addon and one of the internal ones in order for Ember to pick it up in the product

There are *a lot* more pieces at play than this and this change cannot be made at this time

g)
> But if we want uniformity I can update the rest as well.

Please do not.  If you have some available cycles we gladly welcome your assistance but there is a specific order these upgrade tasks need to be addressed in and we can tell you which repo can be worked on next

**Comment by notmessenger** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/126/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Review by notmessenger — APPROVED** [review]

**Pull request merged**
