### PR TITLE
Add closeOnConfirm

### PR DESCRIPTION
**Pull request by sglanzer-fire**
### This project uses [semver](semver.org), please check the scope of this pr:
- [ ] #patch# - backwards-compatible bug fix
- [x] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change
# CHANGELOG
- Added closeOnConfirm (default true) to allow forms to submit and receive an API response prior to close

### CODE REVIEW

**Comment by ember-cli-visual-acceptance** [comment]
# Visual Acceptance tests:

### No changes

**Comment by EWhite613** [comment]
@sglanzer lol wat? Can you do a `git log -n 5` and `git status` in travis (maybe before npm install)? Thinking Travis somehow has the images from the previous build

**Comment by sglanzer-fire** [comment]
@EWhite613 I'll try to find some time, but I have 3-4 other things to finish first, so it'll be next week

**Comment by sglanzer-fire** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/27/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Pull request merged**
