### PR TITLE
fixes for issues #95 and #103

### PR DESCRIPTION
**Pull request by rox163**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* fixes for issues #95 and #103

### CODE REVIEW

**Comment by EWhite613** [comment]
@rox163 Did you mean to add `package-lock.json`?

**Comment by rox163** [comment]
not specifically. i usually do a git add . so that picks up everything. Are we ignoring the lock file?

**Comment by EWhite613** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/115/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Comment by juwara0** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/ciena-frost/ember-frost-modal/pull-request/115/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ciena-frost/ember-frost-modal)

**Pull request merged**
