### PR TITLE
BPSO-91196: help icon feature in modal-dialog-form headers

### PR DESCRIPTION
**Pull request by cstolli**
# Overview

## Summary
Adds the optional help icon feature to the header

## Issue Number(s)
BPSO-91196: help icon feature in modal-dialog-form headers

## Screenshots or recordings
image

## Checklist
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] I have evaluated if the _README.md_ documentation needs to be updated
* [x] I have evaluated if the _/tests/dummy/_ app needs to be modified
* [ ] I have evaluated if DocBlock headers needed to be added or updated
* [x] I have verified that lint and tests pass locally with my changes
* [ ] If a fork of a dependent package had to be made to address the issue this PR closes:
  * [ ] I noted in the fork's _README.md_ the reason the fork was created
  * [ ] I have opened an upstream issue detailing what was deficient about the dependency
  * [ ] I have opened an upstream PR addressing this deficiency
  * [ ] I have opened an issue in this repository to track this PR and schedule the removal of the usage of the fork

# Semver
- [ ] #none#
- [ ] #patch#
- [x] #minor#
- [ ] #major#

# CHANGELOG
* adds a `helpUrl` property to the frost-modal-dialog-form component.  Needed for epic https://agile-jira.ciena.com/browse/BPSO-45504

### CODE REVIEW

**Comment by cstolli** [comment]
@juwara0 @notmessenger this is not perfect yet.  Still need to update the icon.  Just getting a PR open to start the discussion on the proposed implementation.

**Comment by cstolli** [comment]
@notmessenger ok it's better now... I've update the dummy, tests, icon itself, etc.  One thought I had is to not preface the url with `docs/` as that is implementation specific, and the API is more useful if the user can pass any ol' URL there.  thoughts?

**Comment by notmessenger** [comment]
@cstolli I'm not sure if you're still wanting any feedback since you closed this PR but yes I agree - the url should be allowed to be populated with any value, without anything prepended to it (i.e. `/docs`)

**Comment by notmessenger** [comment]
It should also be a MINOR semver since we are

> adding functionality in a backwards-compatible manner

and not adding a

> backwards-compatible bug fix

- https://github.com/ciena-frost/ember-frost-modal/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Review by notmessenger — DISMISSED** [review]

**Pull request merged**
